apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-one
spec:
  selector:
    matchLabels:
      app: app-one
  template:
    metadata:
      labels:
        app: app-one
      annotations:
        version: "tag_version"
    spec:
      containers:
      - name: web-server
        image: rajat965ng/crickplay
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: app-one
spec:
  selector:
    app: app-one
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
