apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-one
spec:
  selector:
    matchLabels:
      app: app-one
  template:
    metadata:
      labels:
        app: app-one
      annotations:
        version: "tag_version"
    spec:
      containers:
      - name: web-server
        image: siralex956/client-gpsso-poc
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: app-one
spec:
  selector:
    app: app-one
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
