kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: backend-ingress
spec:
  rules:
  - http:
      paths:
      - path: /backend
        backend:
          serviceName: app-one-backend
          servicePort: 80